spring:
  application:
    name: local-grpc-client

grpc:
  client:
    local-grpc-server:
#      port: 30390 # k8s
      port: 9898 # local
      enableKeepAlive: true
      keepAliveWithoutCalls: true